### ISSUE TITLE
Automate Release Creation

### ISSUE THREAD

**Issue by replicated-collab-bot-tf** [replicated-collab/joshtest-replicated#10]
### Problem to solve

Automate release creation so that code and YAML in the git repo is always available as an on-prem installable version

### Tasks

- [ ] Determine CI/CD provider (default GitHub actions)
- [ ] Add REPLICATED_APP and REPLICATED_API_TOKEN variables to CI secrets
- [ ] Add `replicated release create --auto -y` to CI workflow
- [ ] Push a change to validate pipeline
- [ ] (best practices discussion) how to set CI pipeline to create version on Beta Channel when a Semver git tag is pushed

### Additional Resources or Documentation

https://docs.replicated.com/vendor/tutorial-installing-with-cli#install-the-replicated-cli
