### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by replicated-collab-bot-tf** [replicated-collab/joshtest-replicated#12]
### Problem to solve

Deploy a kots-managed k8s starter app into a Kubernetes cluster in your cloud environment

### Tasks

- [ ] Complete Lab 0
- [ ] Create your own vendor account
- [ ] publish a release from your starter repo
- [ ] deploy to an internal dev instance in your infrastructure
- [ ] deploy a few updates to the instance

### Additional Resources or Documentation

https://docs.replicated.com/vendor/tutorial-installing-without-existing-cluster
